"""Node definition for the ``sensor_watchdog`` function block (Sensor Watchdog)."""

from __future__ import annotations

from obs.logic.models import NodeTypeDef

NODE_TYPE = NodeTypeDef(
    type="sensor_watchdog",
    label="Sensor Watchdog",
    category="timer",
    description=(
        "Überwacht bis zu 10 Eingänge auf das Ausbleiben neuer Werte. Bleibt ein Eingang länger "
        "als sein konfigurierter Timeout ohne neuen Wert, wird sein Ausgang durch den "
        "konfigurierten Fault-Value ersetzt und ein Fehlertext samt Trigger ausgegeben. Arbeitet "
        "autonom über einen internen Scheduler — unabhängig davon, ob sonst irgendwo im Graphen "
        "ein Ereignis eintritt."
    ),
    # Dynamic — generated by the frontend from the length of the ``inputs`` config array
    # (in_1..in_N / out_1..out_N), plus the two fixed outputs below.
    inputs=[],
    outputs=[],
    config_schema={
        "inputs": {
            "type": "array",
            "label": "Überwachte Eingänge",
            "description": "Bis zu 10 Eingänge, je mit eigenem Timeout und Fault-Value.",
            "items": {
                "type": "object",
                "required": ["timeout_s"],
                "properties": {
                    "label": {"type": "string", "default": "", "label": "Anzeigename"},
                    "timeout_s": {"type": "number", "default": 60, "min": 1, "label": "Timeout (Sekunden)"},
                    "fault_value": {"description": "Ersatzwert nach Ablauf des Timeouts.", "label": "Fault-Value"},
                },
            },
            "default": [{"label": "", "timeout_s": 60, "fault_value": None}],
        },
    },
    color="#b45309",
    help_id="logic-block-timer-sensor-watchdog",
)
