from __future__ import annotations

from obs.logic.nodes.hems import NODE_TYPES
from obs.logic.nodes.hems.surplus import NODE_TYPE as HEMS_SURPLUS
from obs.logic.registry import BUILTIN_NODE_CATEGORIES, get_node_type


def test_metadata():
    assert HEMS_SURPLUS.type == "hems_surplus"
    assert HEMS_SURPLUS.category == "hems"
    assert HEMS_SURPLUS.label == "Überschussregelung"
    assert HEMS_SURPLUS.color.startswith("#")
    assert HEMS_SURPLUS.help_id == "logic-block-hems-surplus"


def test_category_is_registered_and_pure():
    assert NODE_TYPES == (HEMS_SURPLUS,)
    assert "hems" in BUILTIN_NODE_CATEGORIES
    registered = get_node_type("hems_surplus")
    assert registered is not None
    assert registered.has_external_side_effect is False
    assert registered.required_capability is None


def test_ports_are_fully_dynamic():
    # Generated by the frontend from the grid mode and the consumer list.
    assert HEMS_SURPLUS.inputs == []
    assert HEMS_SURPLUS.outputs == []


def test_defaults_match_the_issue():
    schema = HEMS_SURPLUS.config_schema
    assert schema["interval_s"]["default"] == 30
    assert (schema["interval_s"]["min"], schema["interval_s"]["max"]) == (5, 3600)
    assert schema["target_w"]["default"] == 0
    assert schema["on_delay_s"]["default"] == 60
    assert schema["off_delay_s"]["default"] == 180
    assert schema["only_on_change"]["default"] is True
    assert schema["invalid_behavior"]["default"] == "off"
    assert schema["grid_mode"]["enum"] == ["bidirectional", "split", "feed_in_only"]
    assert schema["consumers"]["default"] == []


def test_consumer_schema_covers_the_three_control_types():
    props = HEMS_SURPLUS.config_schema["consumers"]["items"]["properties"]
    assert props["mode"]["enum"] == ["percent", "onoff", "trigger"]
    assert props["rearm"]["enum"] == ["after_lockout", "after_drop", "reset_input"]
    assert props["below_min"]["enum"] == ["off", "hold_min"]
    for key in ("power_w", "min_runtime_s", "min_off_s", "on_delay_s", "off_delay_s", "step", "min_surplus_w", "pulse_s", "lockout_s"):
        assert key in props
