"""Node definition for the ``hems_surplus`` function block (Überschussregelung)."""

from __future__ import annotations

from obs.logic.models import NodeTypeDef

NODE_TYPE = NodeTypeDef(
    type="hems_surplus",
    label="Überschussregelung",
    category="hems",
    description=(
        "HEMS Lite: verteilt den am Netzanschlusspunkt gemessenen Überschuss nach Priorität auf mehrere "
        "Verbraucher — stufenlos regelbar (0–100 %), Ein/Aus oder als einmaliger Trigger. Die Reihenfolge der "
        "Verbraucher ist die Priorität (oberster = höchste); sinkt das Budget, wird von unten nach oben "
        "reduziert. Bei ungültigem oder veraltetem Zähler-Wert gehen alle Ausgänge in den sicheren Zustand "
        "(0 %, aus, kein Trigger). Bei reiner Einspeisemessung kann der Block bei 0 W nicht zwischen "
        "Gleichgewicht und Netzbezug unterscheiden und reduziert deshalb vorsichtig schrittweise."
    ),
    # Dynamic — generated by the frontend from ``grid_mode`` (meter inputs) and the ``consumers`` list
    # (c_<id> output, c_<id>_status, c_<id>_power / _max_power / _reset inputs), plus the fixed
    # global inputs (enable, target, plant_ok) and the diagnostic outputs.
    inputs=[],
    outputs=[],
    config_schema={
        "grid_mode": {
            "type": "string",
            "enum": ["bidirectional", "split", "feed_in_only"],
            "default": "bidirectional",
            "label": "Messart am Netzanschlusspunkt",
        },
        "interval_s": {"type": "number", "default": 30, "min": 5, "max": 3600, "label": "Regelintervall (Sekunden)"},
        "target_w": {"type": "number", "default": 0, "label": "Einspeisereserve am Netzanschlusspunkt (W)"},
        "on_delay_s": {"type": "number", "default": 60, "min": 0, "label": "Einschaltverzögerung (Sekunden)"},
        "off_delay_s": {"type": "number", "default": 180, "min": 0, "label": "Ausschaltverzögerung (Sekunden)"},
        "max_age_s": {
            "type": "number",
            "default": 0,
            "min": 0,
            "label": "Maximales Alter der Zählerwerte (Sekunden, 0 = nicht prüfen)",
        },
        "invalid_behavior": {
            "type": "string",
            "enum": ["off", "hold"],
            "default": "off",
            "label": "Verhalten bei ungültigen Eingangswerten",
        },
        "only_on_change": {"type": "boolean", "default": True, "label": "Nur bei Änderung ausgeben"},
        "consumers": {
            "type": "array",
            "label": "Verbraucher (Reihenfolge = Priorität)",
            "items": {
                "type": "object",
                "required": ["id", "mode"],
                "properties": {
                    "id": {"type": "string", "label": "Stabile ID (Anschlussname)"},
                    "name": {"type": "string", "default": "", "label": "Name"},
                    "active": {"type": "boolean", "default": True, "label": "Aktiv"},
                    "mode": {"type": "string", "enum": ["percent", "onoff", "trigger"], "default": "percent", "label": "Regelart"},
                    "power_source": {"type": "string", "enum": ["fixed", "input"], "default": "fixed", "label": "Leistungsquelle"},
                    "power_w": {"type": "number", "default": 1000, "min": 0, "label": "Nenn-/Maximalleistung (W)"},
                    "min_runtime_s": {"type": "number", "default": 0, "min": 0, "label": "Mindestlaufzeit (Sekunden)"},
                    "min_off_s": {"type": "number", "default": 0, "min": 0, "label": "Mindestauszeit (Sekunden)"},
                    "on_delay_s": {"type": "number", "min": 0, "label": "Einschaltverzögerung (überschreibt global)"},
                    "off_delay_s": {"type": "number", "min": 0, "label": "Ausschaltverzögerung (überschreibt global)"},
                    "min_power_w": {"type": "number", "default": 0, "min": 0, "label": "Mindestleistung (W)"},
                    "min_setpoint": {"type": "number", "default": 0, "min": 0, "max": 100, "label": "Minimaler Sollwert (%)"},
                    "max_setpoint": {"type": "number", "default": 100, "min": 0, "max": 100, "label": "Maximaler Sollwert (%)"},
                    "step": {"type": "number", "default": 1, "min": 0.1, "max": 100, "label": "Schrittweite (%)"},
                    "below_min": {"type": "string", "enum": ["off", "hold_min"], "default": "off", "label": "Unterhalb der Mindestleistung"},
                    "on_threshold_w": {"type": "number", "min": 0, "label": "Einschaltschwelle (W)"},
                    "off_threshold_w": {"type": "number", "min": 0, "label": "Ausschaltschwelle (W)"},
                    "min_surplus_w": {"type": "number", "default": 1000, "min": 0, "label": "Benötigter Mindestüberschuss (W)"},
                    "pulse_s": {"type": "number", "default": 1, "min": 0.1, "label": "Impulsdauer (Sekunden)"},
                    "lockout_s": {"type": "number", "default": 3600, "min": 0, "label": "Sperrzeit nach Auslösung (Sekunden)"},
                    "rearm": {
                        "type": "string",
                        "enum": ["after_lockout", "after_drop", "reset_input"],
                        "default": "after_drop",
                        "label": "Erneute Freigabe",
                    },
                    "reserve_w": {"type": "number", "default": 0, "min": 0, "label": "Reservierte Leistung bei Auslösung (W)"},
                },
            },
            "default": [],
        },
    },
    color="#0d9488",
    help_id="logic-block-hems-surplus",
)
