#!/usr/bin/env python3
"""Generate the DPT keep-rule parity table (#1260).

The .knxproj re-import decides with ``keeps_stored_subtype`` (Python,
``obs/adapters/knx/dpt_registry.py``) whether a DPT already set survives a DPT taken
over from the project; the binding form decides the same with ``keepsStoredSubtype``
(``gui/src/utils/dpt.js``) when a group address is picked from the catalog. Both must
agree. This script writes what the Python implementation answers for every pair of
sample DPTs (main types, subtypes, look-alike prefixes such as DPT1/DPT10.001, empty
values) to ``gui/tests/fixtures/dpt-keep-parity.json``.

``tests/unit/test_dpt_keep_parity_table.py`` fails when the checked-in table is not what
this script produces; ``gui/tests/utils/dpt.spec.js`` fails when ``keepsStoredSubtype``
does not reproduce it.

Usage: tools/with-venv python tools/gen_dpt_keep_parity.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from obs.adapters.knx.dpt_registry import keeps_stored_subtype

TABLE = REPO / "gui" / "tests" / "fixtures" / "dpt-keep-parity.json"

SAMPLES = [
    None,
    "",
    "DPT1",
    "DPT1.001",
    "DPT10",
    "DPT10.001",
    "DPT5",
    "DPT5.001",
    "DPT5.004",
    "DPT7",
    "DPT14",
    "DPT14.056",
    "DPT99",
]


def build_table() -> dict:
    rows = [{"new": new, "stored": stored, "keep": keeps_stored_subtype(new, stored)} for new in SAMPLES for stored in SAMPLES]
    return {
        "_comment": "Generated by tools/gen_dpt_keep_parity.py from keeps_stored_subtype(); do not edit by hand (#1260).",
        "rows": rows,
    }


def render() -> str:
    return json.dumps(build_table(), ensure_ascii=True, indent=1) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when the checked-in table is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = TABLE.read_text(encoding="utf-8") if TABLE.exists() else ""
        if current != content:
            print(f"{TABLE} is stale; run tools/with-venv python tools/gen_dpt_keep_parity.py", file=sys.stderr)
            return 1
        return 0
    TABLE.parent.mkdir(parents=True, exist_ok=True)
    tmp = TABLE.with_suffix(".json.tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(TABLE)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
