#!/usr/bin/env python3
"""Generate the KNX group address formatting parity table (#1296).

The backend renders group addresses with ``format_ga`` (Python), the Admin GUI
with ``formatGa`` (``gui/src/utils/groupAddress.js``). Both must agree. This
script writes the expected results, computed by the Python implementation, to
``gui/tests/fixtures/ga-format-parity.json``:

- the boundary values of every notation, in every style;
- every whitespace character Python's ``str.strip()`` removes, plus a few it
  keeps, around an address;
- invalid texts (out of range, wrong shape, non-ASCII digits, non-strings);
- a fixed sample of raw addresses, each written in all three notations.

``tests/unit/test_ga_format_parity_table.py`` fails when the checked-in table is
not what this script produces; ``gui/tests/utils/groupAddress.spec.js`` fails
when ``formatGa`` does not reproduce it. Invalid inputs are recorded with
``"invalid": true``: ``format_ga`` raises there, ``formatGa`` returns the input
unchanged.

Usage: tools/with-venv python tools/gen_ga_format_parity.py [--check]
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from obs.adapters.knx.group_address import GROUP_ADDRESS_STYLES, InvalidGroupAddress, format_ga

TABLE = REPO / "gui" / "tests" / "fixtures" / "ga-format-parity.json"
SAMPLE_SEED = 1296
SAMPLE_SIZE = 64


def _notations(raw: int) -> list[str]:
    return [f"{raw >> 11}/{(raw >> 8) & 0x7}/{raw & 0xFF}", f"{raw >> 11}/{raw & 0x7FF}", str(raw)]


def _inputs() -> list:
    boundaries = [0, 1, 255, 256, 2047, 2048, 2282, 63487, 63488, 65534, 65535]
    inputs: list = [text for raw in boundaries for text in _notations(raw)]
    inputs += ["01/0/234", "1/00/0234", "00002282", "0/0/0", "0/0", "0"]
    stripped = [chr(c) for c in range(0x110000) if chr(c).isspace()]
    inputs += [f"{ws}1/0/234{ws}" for ws in stripped]
    inputs += ["\u200b1/0/234", "\ufeff1/0/234", "1/ 0/234", "1 /234"]  # kept by str.strip(), so invalid
    inputs += ["32/0/0", "31/8/0", "31/7/256", "32/0", "31/2048", "65536", "-1", "1/-1/2", "+1/0/2"]
    inputs += ["", " ", "/", "1//2", "1/2/3/4", "1/2/", "a/b/c", "1/0/x", "1.0.234", "1/0/234 x"]
    inputs += ["\u0661/0/234", "\uff11/0/234", "\u00b2"]  # Unicode digits: Python's isdigit() accepts them, ASCII only counts
    inputs += [None, 2282, ["1/0/234"]]
    rng = random.Random(SAMPLE_SEED)
    for raw in sorted(rng.sample(range(65536), SAMPLE_SIZE)):
        inputs += _notations(raw)
    return inputs


def build_table() -> dict:
    rows = []
    for value in _inputs():
        expected: dict[str, str] = {}
        for style in GROUP_ADDRESS_STYLES:
            try:
                expected[style] = format_ga(value, style)
            except InvalidGroupAddress:
                expected = {}
                break
        rows.append({"input": value, "invalid": True} if not expected else {"input": value, "expected": expected})
    return {
        "_comment": "Generated by tools/gen_ga_format_parity.py from format_ga(); do not edit by hand (#1296).",
        "styles": list(GROUP_ADDRESS_STYLES),
        "rows": rows,
    }


def render() -> str:
    return json.dumps(build_table(), ensure_ascii=True, indent=1) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when the checked-in table is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        current = TABLE.read_text(encoding="utf-8") if TABLE.exists() else ""
        if current != content:
            print(f"{TABLE} is stale; run tools/with-venv python tools/gen_ga_format_parity.py", file=sys.stderr)
            return 1
        return 0
    TABLE.parent.mkdir(parents=True, exist_ok=True)
    tmp = TABLE.with_suffix(".json.tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(TABLE)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
